// <auto-generated />
using System;
using BASAccountManager.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BASAccountManager.Migrations
{
    [DbContext(typeof(AMContext))]
    [Migration("20240120025321_AddNewColumns")]
    partial class AddNewColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BASAccountManager.DB.Models.DBBASExeption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("ExeptionMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExeptionTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProxyId")
                        .HasColumnType("int");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ProxyId");

                    b.HasIndex("TaskId");

                    b.ToTable("BASExeption");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("APIToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmailType")
                        .HasColumnType("int");

                    b.Property<string>("MailDomain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Email");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBFillingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AboutMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ClosedAccount")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableRecomendations")
                        .HasColumnType("bit");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FillingData");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBFollow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FollowStatus")
                        .HasColumnType("int");

                    b.Property<int>("RecipientAccountId")
                        .HasColumnType("int");

                    b.Property<int>("SenderAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipientAccountId");

                    b.HasIndex("SenderAccountId");

                    b.ToTable("Follow");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBInstAccountGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InstAccountGroup");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBInstagramAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FillingDataId")
                        .HasColumnType("int");

                    b.Property<int>("InstGroupId")
                        .HasColumnType("int");

                    b.Property<string>("InstanceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FillingDataId");

                    b.HasIndex("InstGroupId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("InstAccount");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PostCommentGroupId")
                        .HasColumnType("int");

                    b.Property<int>("PostStatus")
                        .HasColumnType("int");

                    b.Property<string>("PostURI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequiredCountComments")
                        .HasColumnType("int");

                    b.Property<int>("RequiredCountLikes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PostCommentGroupId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBProxy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ChangeIpURI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProxyGroupId")
                        .HasColumnType("int");

                    b.Property<int>("ProxyStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProxyGroupId");

                    b.ToTable("Proxy");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBProxyGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProxyGroup");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBSMSActivation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("APIKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SMSActivation");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientTaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProxyGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.Property<string>("UsefulData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBWorkerTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstanceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProxyId")
                        .HasColumnType("int");

                    b.Property<int?>("RegistrationVerifyResoursesType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.Property<string>("UsefulData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ProxyId");

                    b.HasIndex("TaskId");

                    b.ToTable("WorkerTask");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.Post.DBComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostCommentGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostCommentGroupId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.Post.DBInstPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstPostStatus")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("PostURI")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostingErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PostId");

                    b.HasIndex("PostURI")
                        .IsUnique()
                        .HasFilter("[PostURI] IS NOT NULL");

                    b.ToTable("InstPost");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.Post.DBPostComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<int>("CommentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CommentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int?>("SenderAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("SenderAccountId");

                    b.ToTable("PostComment");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.Post.DBPostCommentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CommentGroup");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.Post.DBPostGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccountGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AccountGroupId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PostGroup");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.Post.DBPostLikes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LikeStatus")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int?>("SenderAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("SenderAccountId");

                    b.ToTable("PostLike");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBBASExeption", b =>
                {
                    b.HasOne("BASAccountManager.DB.Models.DBInstagramAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("BASAccountManager.DB.Models.DBProxy", "Proxy")
                        .WithMany("BASExeptions")
                        .HasForeignKey("ProxyId");

                    b.HasOne("BASAccountManager.DB.Models.DBTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId");

                    b.Navigation("Account");

                    b.Navigation("Proxy");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBFollow", b =>
                {
                    b.HasOne("BASAccountManager.DB.Models.DBInstagramAccount", "RecipientAccount")
                        .WithMany()
                        .HasForeignKey("RecipientAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BASAccountManager.DB.Models.DBInstagramAccount", "SenderAccount")
                        .WithMany()
                        .HasForeignKey("SenderAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipientAccount");

                    b.Navigation("SenderAccount");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBInstagramAccount", b =>
                {
                    b.HasOne("BASAccountManager.DB.Models.DBFillingData", "FillingData")
                        .WithMany("ListAccounts")
                        .HasForeignKey("FillingDataId");

                    b.HasOne("BASAccountManager.DB.Models.DBInstAccountGroup", "InstGroup")
                        .WithMany("InstAccounts")
                        .HasForeignKey("InstGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FillingData");

                    b.Navigation("InstGroup");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBPost", b =>
                {
                    b.HasOne("BASAccountManager.DB.Models.Post.DBPostGroup", "Group")
                        .WithMany("ListPost")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BASAccountManager.DB.Models.Post.DBPostCommentGroup", "PostCommentGroup")
                        .WithMany("ListPost")
                        .HasForeignKey("PostCommentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("PostCommentGroup");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBProxy", b =>
                {
                    b.HasOne("BASAccountManager.DB.Models.DBProxyGroup", "ProxyGroup")
                        .WithMany("Proxies")
                        .HasForeignKey("ProxyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProxyGroup");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBWorkerTask", b =>
                {
                    b.HasOne("BASAccountManager.DB.Models.DBInstagramAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BASAccountManager.DB.Models.DBProxy", "Proxy")
                        .WithMany()
                        .HasForeignKey("ProxyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BASAccountManager.DB.Models.DBTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Proxy");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.Post.DBComment", b =>
                {
                    b.HasOne("BASAccountManager.DB.Models.Post.DBPostCommentGroup", "PostCommentGroup")
                        .WithMany("ListComment")
                        .HasForeignKey("PostCommentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostCommentGroup");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.Post.DBInstPost", b =>
                {
                    b.HasOne("BASAccountManager.DB.Models.DBInstagramAccount", "Account")
                        .WithMany("ListPost")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BASAccountManager.DB.Models.DBPost", "Post")
                        .WithMany("ListPost")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.Post.DBPostComment", b =>
                {
                    b.HasOne("BASAccountManager.DB.Models.Post.DBComment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BASAccountManager.DB.Models.Post.DBInstPost", "Post")
                        .WithMany("ListComment")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BASAccountManager.DB.Models.DBInstagramAccount", "SenderAccount")
                        .WithMany("ListComments")
                        .HasForeignKey("SenderAccountId");

                    b.Navigation("Comment");

                    b.Navigation("Post");

                    b.Navigation("SenderAccount");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.Post.DBPostGroup", b =>
                {
                    b.HasOne("BASAccountManager.DB.Models.DBInstAccountGroup", "AccountGroup")
                        .WithMany()
                        .HasForeignKey("AccountGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountGroup");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.Post.DBPostLikes", b =>
                {
                    b.HasOne("BASAccountManager.DB.Models.Post.DBInstPost", "Post")
                        .WithMany("ListLikes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BASAccountManager.DB.Models.DBInstagramAccount", "SenderAccount")
                        .WithMany("ListLikes")
                        .HasForeignKey("SenderAccountId");

                    b.Navigation("Post");

                    b.Navigation("SenderAccount");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBFillingData", b =>
                {
                    b.Navigation("ListAccounts");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBInstAccountGroup", b =>
                {
                    b.Navigation("InstAccounts");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBInstagramAccount", b =>
                {
                    b.Navigation("ListComments");

                    b.Navigation("ListLikes");

                    b.Navigation("ListPost");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBPost", b =>
                {
                    b.Navigation("ListPost");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBProxy", b =>
                {
                    b.Navigation("BASExeptions");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.DBProxyGroup", b =>
                {
                    b.Navigation("Proxies");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.Post.DBInstPost", b =>
                {
                    b.Navigation("ListComment");

                    b.Navigation("ListLikes");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.Post.DBPostCommentGroup", b =>
                {
                    b.Navigation("ListComment");

                    b.Navigation("ListPost");
                });

            modelBuilder.Entity("BASAccountManager.DB.Models.Post.DBPostGroup", b =>
                {
                    b.Navigation("ListPost");
                });
#pragma warning restore 612, 618
        }
    }
}
